# VVVV I modified the file B)
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ 
      ./hardware-configuration.nix
  ];

  # Graphics Drivers
  hardware.graphics = {
    enable = true;
  };
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true;
    open = true;
    nvidiaSettings = true;
  };

  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "radeonsi";
    LIBVA_DEVICE = "/dev/dri/by-path/pci-0000:0f:00.0-render";
  };

  boot.kernelParams = [
    "nvidia.NVreg_PreserveVideoMemoryAllocations=1"  # May cause instability, remove if so
  ];  

  # Filesystem options
  fileSystems."/".options = lib.mkForce [ "subvol=@" "compress=zstd:3" "noatime" ];
  fileSystems."/home".options = lib.mkForce [ "subvol=@home" "compress=zstd:3" "noatime" ];
  #fileSystems."/swap".options = lib.mkForce [ "subvol=@swap" "compress=no" "nodatacow" "noatime" ];
  #swapDevices = lib.mkForce [
  #    {
  #      device = "/swap/swapfile";
  #      size = 4 * 1024;
  #    }
  #];
}
