# VVVV I modified the file B)
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ 
      ./hardware-configuration.nix
  ];

  # Graphics Drivers
  hardware.graphics = {
    enable = true;
  };
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    prime = {
      reverseSync.enable = true;
      offload.enable = true;
      offload.enableOffloadCmd = true;
      amdgpuBusId = "PCI:15:0:0";
      nvidiaBusId = "PCI:1:0:0";
    };
    powerManagement.enable = true;
    powerManagement.finegrained = true;
    open = true;
    nvidiaSettings = true;
  };

  environment.sessionVariables = {
    WLR_DRM_DEVICES = "/dev/dri/card2";
    MESA_LOADER_DRIVER_OVERRIDE = "radeonsi";
    __GLX_VENDOR_LIBRARY_NAME = "mesa";
    VK_ICD_FILENAMES = "/run/opengl-driver/share/vulkan/icd.d/radeon_icd.x86_64.json";
    LIBVA_DRIVER_NAME = "radeonsi";
  };

  boot.kernelParams = [
    "nvidia.NVreg_PreserveVideoMemoryAllocations=1"  # May cause instability, remove if so
  ];  

  # Filesystem options
  fileSystems."/".options = lib.mkForce [ "subvol=@" "compress=zstd:3" "noatime" ];
  fileSystems."/home".options = lib.mkForce [ "subvol=@home" "compress=zstd:3" "noatime" ];
  fileSystems."/swap".options = lib.mkForce [ "subvol=@swap" "compress=no" "nodatacow" "noatime" ];
  swapDevices = lib.mkForce [
      {
        device = "/swap/swapfile";
        size = 4 * 1024;
      }
  ];
}
