# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-40c54ba6-1e66-4927-8f0c-5d2f72439a51";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-40c54ba6-1e66-4927-8f0c-5d2f72439a51".device =
    "/dev/disk/by-uuid/40c54ba6-1e66-4927-8f0c-5d2f72439a51";

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-40c54ba6-1e66-4927-8f0c-5d2f72439a51";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-40c54ba6-1e66-4927-8f0c-5d2f72439a51";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/92F1-E9D8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/luks-40c54ba6-1e66-4927-8f0c-5d2f72439a51";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
