# VVVV I modified the file B)
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  main-fs = "/dev/disk/by-uuid/699fd88c-cb21-43d4-bd9d-a6192668b2c8";
  boot-fs = "/dev/disk/by-uuid/186E-7568";
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Graphics Drivers
  hardware.graphics = {
    enable = true;
  };
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true;
    open = true;
    nvidiaSettings = true;
  };

  swapDevices =
    [
      {
        device = "/swap/swapfile";
        size = 4 * 1024;
      }
    ];

  fileSystems."/" =
    { device = main-fs;
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" ];
    };
  fileSystems."/home" =
    { device = main-fs;
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" ];
    };
  fileSystems."/swap" =
    { device = main-fs;
      fsType = "btrfs";
      options = [ "subvol=@swap" "nodatacow" "noatime" ];
    };

  fileSystems."/boot" =
    { device = boot-fs;
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
