# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  main-fs = "/dev/disk/by-uuid/5d5df10a-d424-42ed-8730-8107905d4182";
  boot-fs = "/dev/disk/by-uuid/4017-4DD4";
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  services.xserver.videoDrivers = [ "amdgpu" ];

  # Suspend-then-hibernate
  services.logind.settings.Login = {
    HandleLidSwitch = "suspend";
    HandleLidSwitchDocked = "ignore";
    PowerKey = "suspend";
  };
  systemd.sleep.extraConfig = ''
    AllowSuspend=yes
    AllowHibernation=yes
    AllowSuspendThenHibernate=yes
    HibernateDelaySec=10min
  '';

  # Hibernation
  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 20 * 1024; 
    }
  ];
  boot.resumeDevice = main-fs;
  boot.kernelParams = [
    "resume_offset=8829848" 
  ];

  fileSystems."/" =
    { device = main-fs;
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };
  fileSystems."/home" =
    { device = main-fs;
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };
  fileSystems."/swap" =
    { device = main-fs;
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/boot" =
    { device = boot-fs;
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
